app/base/urls.py
from django.urls import path

from app.base import views 

app_name = 'base'

urlpatterns = [
    # path('', views.home_page, name='home_page'),
    path('',views.Home.as_view(),name="home")
]

app/inventory/urls.py
# app/inventory/urls.py

# Import from django/third parties modules
from django.urls import path

from app.inventory.views import (
    CategoryView, CategoryNew, 
    CategoryEdit, CategoryDelete,
    SubCategoryView, SubCategoryNew) 

app_name = 'inventory'

urlpatterns = [
    path('categories',CategoryView.as_view(),name="category_list"),
    path('categories/new',CategoryNew.as_view(),name="category_new"),
    path('categories/edit/<int:pk>',CategoryEdit.as_view(),name="category_edit"),
    path('categories/delete/<int:pk>',CategoryDelete.as_view(),name="category_delete"),

    path('subcategories',SubCategoryView.as_view(),name="sub_category_list"),
    path('subcategories/new',SubCategoryNew.as_view(),name="sub_category_new"),

]

app/users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from app.users import views 

app_name = 'users'

urlpatterns = [
    # path('login',views.Login.as_view(),name="login")
    path('login/',auth_views.LoginView.as_view(
            template_name='users/login.html'),name="login"),
    path('logout/',auth_views.LogoutView.as_view(
            template_name='users/logout.html'),name="logout")
]

config_pos/urls.py
from django.contrib import admin
from django.urls import path, include 

urlpatterns = [
    path('admin/', admin.site.urls),

    # users app
    path('', include(('app.users.urls','users'), namespace='users')),

    # base app
    path('', include(('app.base.urls','base'), namespace='base')),

    # inventory app
    path('inventory/', include(('app.inventory.urls','inventory'), namespace='inventory')),
] 

app/base/models.py
# app/base/models.py

# Import from django/third parties modules
from django.db import models
from django.contrib.auth.models import User 

# Import from locals

# Create your models here.


class AbstractModel(models.Model):

	"""
	AbstractModel.
	Model ini tidak akan nampak, karena kelas ini 
	tidak bisa dijalankan dengan perintah makemigrations
	dan migrate.

	Model ini adalah sebuah Model layaknya sebuah 'pola'
	yang bisa digunakan oleh Model-model lainnya di dalam
	aplikasi ini.

	Intinya, field yang ada dalam AbstractModel ini,
	akan tersedia secara otomatis (DRF) bila
	AbstractModel ini digunakan oleh Model lain
	yang akan dibuat.
	"""

	state = models.BooleanField(default=True)
	date_created = models.DateTimeField(auto_now_add=True)
	date_modified = models.DateTimeField(auto_now=True)
	user_creation = models.ForeignKey(User,on_delete=models.CASCADE)
	user_modification = models.IntegerField(blank=True,null=True)

	class Meta:
		abstract = True

app/inventory/models.py
# app/inventory/models.py

# Import from django/third parties modules
from django.db import models

# Import from locals
from app.base.models import AbstractModel

# Create your models here.

# MODEL:Category 
class Category(AbstractModel):

	description = models.CharField(
		max_length=100,
		help_text='Description of the Category',
		unique=True
	)

	def __str__(self):
		return '{}'.format(self.description)

	def save(self):
		self.description = self.description.upper()
		super(Category, self).save()

	class Meta:
		verbose_name_plural = 'Categories'


# MODEL:SubCategory 
class SubCategory(AbstractModel):

	category = models.ForeignKey(Category, on_delete=models.CASCADE)
	description = models.CharField(
		max_length=100,
		help_text='Description of the Sub Category',
	)

	def __str__(self):
		return '{}:{}'.format(self.category.description,self.description)

	def save(self):
		self.description = self.description.upper()
		super(SubCategory, self).save()

	class Meta:
		verbose_name_plural = 'Sub Categories'
		unique_together = ('category','description')

app/inventory/forms.py
# app/inventory/forms.py

# Import django/third parties modules
from django import forms 

# Import from locals
from app.inventory.models import Category, SubCategory

# Create your form here

class CategoryForm(forms.ModelForm):
	class Meta:
		model=Category
		fields=['description','state']
		label={'description':'Description of the Category','state':'State'}
		widget={'description': forms.TextInput}

	def __init__(self, *args, **kwargs):
	    super().__init__(*args, **kwargs)
	    for field in iter(self.fields):
	    	self.fields[field].widget.attrs.update({
	    		'class':'form-control'
	    	})


class SubCategoryForm(forms.ModelForm):
	class Meta:
		model=SubCategory
		fields=['category','description','state']
		label={'description':'Description of the Sub Category','state':'State'}
		widget={'description': forms.TextInput}

	def __init__(self, *args, **kwargs):
	    super().__init__(*args, **kwargs)
	    for field in iter(self.fields):
	    	self.fields[field].widget.attrs.update({
	    		'class':'form-control'
	    	})
	    self.fields["category"].empty_label = "Select Category"

app/base/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView 

# Create your views here.

# def home_page(request):
# 	return render(request, 'base/index.html')

class Home(LoginRequiredMixin, TemplateView):
	template_name = 'base/index.html'
	# login_url = '/admin'
	login_url = 'users:login'

app/inventory/views.py
# app/inventory/views.py

# Import django/third parties modules
from django.shortcuts import render
from django.views.generic import ListView, CreateView, UpdateView, DeleteView 
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy 

# Import from locals
from app.inventory.models import Category, SubCategory 
from app.inventory.forms import CategoryForm, SubCategoryForm

# Create your views here.

class CategoryView(LoginRequiredMixin,ListView):
	model = Category
	template_name = 'inventory/category_list.html'
	context_object_name = 'obj'
	login_url = 'users:login' 


class CategoryNew(LoginRequiredMixin,CreateView):
	model=Category
	template_name="inventory/category_form.html"
	context_object_name="obj"
	form_class=CategoryForm
	success_url=reverse_lazy("inventory:category_list")
	login_url="users:login"

	def form_valid(self, form):
		form.instance.user_creation = self.request.user 
		return super().form_valid(form)


class CategoryEdit(LoginRequiredMixin,UpdateView):
	model=Category
	template_name="inventory/category_form.html"
	context_object_name="obj"
	form_class=CategoryForm
	success_url=reverse_lazy("inventory:category_list")
	login_url="users:login"

	def form_valid(self, form):
		form.instance.user_modification = self.request.user.id 
		return super().form_valid(form)


class CategoryDelete(LoginRequiredMixin,DeleteView):
	model=Category
	template_name="inventory/category_delete.html"
	context_object_name="obj"
	success_url=reverse_lazy("inventory:category_list")


class SubCategoryView(LoginRequiredMixin,ListView):
	model = SubCategory
	template_name = 'inventory/sub_category_list.html'
	context_object_name = 'obj'
	login_url = 'users:login' 


class SubCategoryNew(LoginRequiredMixin,CreateView):
	model=SubCategory
	template_name="inventory/sub_category_form.html"
	context_object_name="obj"
	form_class=SubCategoryForm
	success_url=reverse_lazy("inventory:sub_category_list")
	login_url="users:login"

	def form_valid(self, form):
		form.instance.user_creation = self.request.user 
		return super().form_valid(form)

app/users/views.py
from django.shortcuts import render
from django.views.generic import TemplateView 

# Create your views here.

# def home_page(request):
# 	return render(request, 'base/index.html')

# class Login(TemplateView):
# 	template_name = 'users/login.html'

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    {% include 'partials/head.html' %}
</head>

<body id="page-top">

    {% include 'partials/sidebar.html' %}

    {% include 'partials/top_navbar.html' %}


    {% block content %}
    {% endblock content %}


    {% include 'partials/footer.html' %}
 
</body>
</html>

templates/base/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}


<div class="container-fluid">
    <h1 class="h3 mb-4 text-gray-800">Blank Page</h1>
</div>


{% endblock content %}

templates/inventory/category_delete.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<form method="POST" class="form-inline">
    {% csrf_token %}
    <div class="col-xl-3 col-md-6 mb-4">
      <div class="card border-left-danger shadow h-100 py-2">
        <div class="card-body">
          <div class="row no-gutters align-items-center">
            <div class="col mr-2">
              <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">Delete {{ obj.description }}</div>
              <button type="submit" class="btn btn-danger">
            	<i class="far fa-question-circle"></i>  	
              </span>Yes, Delete</button>
              <a href="{% url 'inventory:category_list' %}" class="btn btn-success"><span class="fa fa-undo"></span>Cancel</a>
            </div>
            <div class="col-auto">
              <i class="fas fa-comments fa-2x text-gray-300"></i>
            </div>
          </div>
        </div>
      </div>
    </div>
</form>
{% endblock content %}

templates/inventory/category_form.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<form method="POST" class="form-inline">
    {% csrf_token%}
    <div class="col-xl-6 col-md-6 mb-6">
        <div class="card border-left-primary shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">New category</div>
                        
                        <div class="row">
                            <div class="col-10">
                                <div class="input-group">
                                    <input 
                                        type="text" 
                                        name="description"
                                        maxlength="100"
                                        class="form-control"
                                        required
                                        id="id_description"
                                        placeholder="Description"
                                        value="">
                                </div>
                            </div>
                            <div class="col-2">
                                <div class="form-group">
                                    <label for="id_state" style="margin-right:5px;">State</label>
                                    <input type="checkbox" name="state"  class="form-control" id="is_state" checked>
                                </div>
                                
                            </div>
                            <!-- {{ form.as_p}} -->
                        </div><br>
                        
                        <div class="dropdown-divider"></div>
                        <div class="row">
                            <div class="col">
                                <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span>Save</button>
                                <a href="{% url 'inventory:category_list' %}" class="btn btn-success"><span class="fa fa-undo"></span>Cancel</a>
                            </div>
                        </div>
                    </div>

                    

                    
                </div>
            </div>
        </div>
    </div>
</form>
{% endblock content %}

templates/inventory/category_form_ori_good.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<form method="POST" class="form-inline">
    {% csrf_token%}
    <div class="col-xl-6 col-md-6 mb-6">
        <div class="card border-left-primary shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">New category</div>
                        
                        <div class="row">
                            <div class="col-10">
                                <div class="input-group">
                                    <input 
                                        type="text" 
                                        name="description"
                                        maxlength="100"
                                        class="form-control"
                                        required
                                        id="id_description"
                                        placeholder="Description"
                                        value="">
                                </div>
                            </div>
                            <div class="col-2">
                                <div class="form-group">
                                    <label for="id_state" style="margin-right:5px;">State</label>
                                    <input type="checkbox" name="state"  class="form-control" id="is_state" checked>
                                </div>
                                
                            </div>
                            <!-- {{ form.as_p}} -->
                        </div><br>
                        
                        <div class="dropdown-divider"></div>
                        <div class="row">
                            <div class="col">
                                <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span>Save</button>
                                <a href="{% url 'inventory:category_list' %}" class="btn btn-success"><span class="fa fa-undo"></span>Cancel</a>
                            </div>
                        </div>
                    </div>

                    

                    
                </div>
            </div>
        </div>
    </div>
</form>
{% endblock content %}

templates/inventory/category_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
                <!-- Begin Page Content -->
                <div class="container-fluid">
                    <div class="card shadow mb-4">

                        <!-- Header begin -->
                        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                            <h6 class="m-0 font-weight-bold text-primary">Category List</h6>
                            <div class="dropdown no-arrow">
                                <a class="dropdown-toggle" href="" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                                    <div class="dropdown-header">Actions</div>
                                    <a class="dropdown-item" href="{% url 'inventory:category_new' %}">
                                        <i class="far fa-calendar-plus"></i> 
                                        New
                                    </a>
                                    <a class="dropdown-item" href="">Another Action</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="">Something else here</a>
                                </div>
                            </div>
                        </div>
                        <!-- Header close -->

                        <!-- Card-body begin -->
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                    <thead>
                                        <tr>
                                            <th>Id</th>
                                            <th>Description</th>
                                            <th>State</th>
                                            <th>Date Created</th>
                                            <th>Date Modified</th>
                                            <th class="all">Actions</th>
                                        </tr>
                                    </thead>
                                    <tfoot>
                                        <tr>
                                            <th>Id</th>
                                            <th>Description</th>
                                            <th>State</th>
                                            <th>Date Created</th>
                                            <th>Date Modified</th>
                                            <th class="all">Actions</th>
                                        </tr>
                                    </tfoot>
                                    <tbody>
                                        {% for item in obj %}
                                        <tr>
                                            <td>{{ item.id }}</td>
                                            <td>{{ item.description }}</td>
                                            <td>{{ item.state|yesno:"Active,Inactive" }}</td>
                                            <td>{{ item.date_created|date:"d/m/Y H:i:s" }}</td>
                                            <td>{{ item.date_modified|date:"d/m/Y H:i:s" }}</td>
                                            <td>
                                                <a href="{% url 'inventory:category_edit' item.id %}" class="btn btn-warning btn-circle" role='button'>
                                                    <i class="far fa-edit"></i>
                                                </a>
                                                <a href="{% url 'inventory:category_delete' item.id %}" class="btn btn-warning btn-circle" role='button'>
                                                    <i class="far fa-trash-alt"></i>
                                                </a>
                                            </td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <!-- Card-body close -->

                    </div>
                </div>
                <!-- /.container-fluid -->
{% endblock content %}

{% block js_page %}
<script>
    // {# Call the dataTables jQuery plugin #}
    $(ducument).ready(function(){
        $('.table').DataTable();
    });
</script>
{% endblock js_page %}

templates/inventory/sub_category_form.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<form method="POST" class="form-inline">
    {% csrf_token%}
    <div class="col-xl-12 col-md-12 mb-12">
        {# Update category #}
        {% if obj %}
        <div class="card border-left-warning shadow h-100 py-2">
        {% else %}
        <div class="card border-left-primary shadow h-100 py-2">
        {% endif %}
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                            {% if obj %} Edit {% else %} New {% endif %} Sub Category
                        </div>
                        
                        <div class="row">
                            <div class="col-5">
                                <div class="input-group">
                                    <!--  <input 
                                        type="text" 
                                        name="description"
                                        maxlength="100"
                                        class="form-control"
                                        required
                                        id="id_description"
                                        placeholder="Description"
                                        value="{% if obj %} {{ obj.description }} {% endif %}">  -->
                                        {{ form.category }}
                                </div>
                            </div>
                            <div class="col-5">
                                <div class="input-group">
                                    <!-- <input 
                                        type="text" 
                                        name="description"
                                        maxlength="100"
                                        class="form-control"
                                        required
                                        id="id_description"
                                        placeholder="Description"
                                        value="{% if obj %} {{ obj.description }} {% endif %}">  -->

                                        {{ form.description }}
                                </div>
                            </div>
                            <div class="col-2">
                                <div class="form-group">
                                    <!-- <label for="id_state" style="margin-right:5px;">State</label>
                                    <input type="checkbox" name="state"  class="form-control" id="is_state" 
                                       {% if obj.state %} checked {% endif %} >  -->

                                       {{ form.state }}
                                </div>
                                
                            </div>
                            <!-- {{ form.as_p}} -->
                        </div><br>
                        
                        <div class="dropdown-divider"></div>
                        <div class="row">
                            <div class="col">
                                <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span>Save</button>
                                <a href="{% url 'inventory:sub_category_list' %}" class="btn btn-success"><span class="fa fa-undo"></span>Cancel</a>
                            </div>
                        </div>
                    </div>

                    

                    
                </div>
            </div>
        </div>
    </div>
</form>
{% endblock content %}

templates/inventory/sub_category_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
                <!-- Begin Page Content -->
                <div class="container-fluid">
                    <div class="card shadow mb-4">

                        <!-- Header begin -->
                        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                            <h6 class="m-0 font-weight-bold text-primary">Sub Category List</h6>
                            <div class="dropdown no-arrow">
                                <a class="dropdown-toggle" href="" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                                    <div class="dropdown-header">Actions</div>
                                    <a class="dropdown-item" href="{% url 'inventory:sub_category_new' %}">
                                        <i class="far fa-calendar-plus"></i> 
                                        New
                                    </a>
                                </div>
                            </div>
                        </div>
                        <!-- Header close -->

                        <!-- Card-body begin -->
                        <div class="card-body">
                            <div class="table-responsive">
                                {% if not obj %}
                                <div class="alert alert-info">No sub categories</div>
                                {% else %}
                                <!-- <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0"> -->
                                <table class="table table-striped table-hover" id="dataTable" width="100%" cellspacing="0">
                                    <thead>
                                        <tr>
                                            <th>Category</th>
                                            <th>Id</th>
                                            <th>Description</th>
                                            <th>State</th>
                                            <th>Date Created</th>
                                            <th>Date Modified</th>
                                            <th class="all">Actions</th>
                                        </tr>
                                    </thead>
                                    <tfoot>
                                        <tr>
                                            <th>Id</th>
                                            <th>Description</th>
                                            <th>State</th>
                                            <th>Date Created</th>
                                            <th>Date Modified</th>
                                            <th class="all">Actions</th>
                                        </tr>
                                    </tfoot>
                                    <tbody>
                                        {% for item in obj %}
                                        <tr>
                                            <td>{{ item.category }}</td>
                                            <td>{{ item.id }}</td>
                                            <td>{{ item.description }}</td>
                                            <td>{{ item.state|yesno:"Active,Inactive" }}</td>
                                            <td>{{ item.date_created|date:"d/m/Y H:i:s" }}</td>
                                            <td>{{ item.date_modified|date:"d/m/Y H:i:s" }}</td>
                                            <td>
                                                <a href="{% url 'inventory:category_edit' item.id %}" class="btn btn-warning btn-circle" role='button'>
                                                    <i class="far fa-edit"></i>
                                                </a>
                                                <a href="{% url 'inventory:category_delete' item.id %}" class="btn btn-warning btn-circle" role='button'>
                                                    <i class="far fa-trash-alt"></i>
                                                </a>
                                            </td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                                {% endif %}
                            </div>
                        </div>
                        <!-- Card-body close -->

                    </div>
                </div>
                <!-- /.container-fluid -->
{% endblock content %}

{% block js_page %}
<script>
    // {# Call the dataTables jQuery plugin #}
    $(ducument).ready(function(){
        $('.table').DataTable();
    });
</script>
{% endblock js_page %}

templates/partials/footer.html
{% load static %}

            </div>
            <!-- End of Main Content -->
            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Your Website 2019</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->
        </div>
        <!-- End of Content Wrapper -->
    </div>
    <!-- End of Page Wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
    </a>
    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="{% url 'users:login' %}">Logout</a>
                </div>
            </div>
        </div>
    </div>
    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- Core plugin JavaScript-->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>
    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/sb-admin-2.min.js' %}"></script>
    <!-- Page level plugins -->
    <script src="{% static 'vendor/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>
    <!-- Page level custom scripts -->
    <script src="/static/js/demo/datatables-demo.js"></script>

    {# Call the dataTables jQuery plugin in category_list.html #}
    {% block js_page %}{% endblock js_page %}

templates/partials/head.html
{% load static %}    

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>SB Admin 2 - Blank</title>
    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">
    <!-- Custom styles for this page -->
    <link href="{% static 'vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">

templates/users/logout.html
Logged out

Log in again